//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_ID { get; set; }
        public string Emp_First_Name { get; set; }
        public string Emp_Last_Name { get; set; }
        public string Emp_Email_ID { get; set; }
        public string Emp_Mobile_Number { get; set; }
        public int Emp_State_ID { get; set; }
        public int Emp_City_ID { get; set; }
        public int Emp_Skill_ID { get; set; }
        public System.DateTime Emp_DOB { get; set; }
        public Nullable<System.DateTime> Emp_DOJ { get; set; }
        public int Emp_Dept_ID { get; set; }
    }
}
