//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int State_ID { get; set; }
        public string State_Name { get; set; }
    }
}
